metamath/metamath-knife

src/database.rs, src/outline.rs, src/parser.rs
This isolates some changes made for `Outline` from #9.
=> Changes to `Outline`

src/outline.rs
I forgot to isolate this part in #14
=> Outline tree is now stored using Arc's.

src/formula.rs, src/formula_tests.rs, src/grammar.rs, src/grammar_tests.rs, src/main.rs, src/tree.rs
This introduces formula unification and substitution, which are straightforward once the formula syntax tree is known.
This PR also comes along with a handful of simple tests cases for unification and substitution.
=> Unification and Substitution

.github/workflows/verify.yml, src/export.rs, src/formula.rs, src/grammar.rs, src/grammar_tests.rs, src/lib.rs, src/main.rs, src/proof.rs
And return 1 on any warning or error so that the CI fails.
=> Add a test of the official set.mm to the CI

src/proof.rs
This shall fix issue #27 .
- essentials are not added to the list of statements to be put in the parens,
- instead, they are prepended to that list after it is output, so that they are found in later lookups,
- there are cases where non-mandatory floating hypothesis are used. The corresponding statements _are_ added to the parens list
The compressed proofs created with this new version are accepted by the Metamath program and MMJ2.
=> Fixes compressed proof generation with essential hypotheses

.github/workflows/verify.yml
=> CI now uses set.mm from the master branch

src/outline.rs
Extracted from @tirix 's addition to #59 .
=> Outline bugfix

src/formula_tests.rs, src/grammar_tests.rs, src/outline.rs, src/tree.rs
This adds the ability to retrieve the next outline node for any node.
This could probably be re-written in a nicer way using statement address iterators introduced in #61 , I'll look into that.
=> Next outline element

src/formula.rs, src/formula_tests.rs, src/grammar_tests.rs
As suggested in a [review comment](https://github.com/david-a-wheeler/metamath-knife/pull/65#discussion_r790423660) in #65.
=> S-Expressions

src/grammar.rs, src/line_cache.rs
Follows suggestions from recently added Clippy lints.
=> New clippy lints

src/diag.rs, src/grammar.rs, src/grammar_tests.rs, src/outline.rs
And associated tests.
This fixes [metamath_vspa#11](https://github.com/tirix/metamath-vspa/issues/11)
=> Fix for metamath_vspa#11

src/comment_parser.rs, src/line_cache.rs, src/nameck.rs, src/proof.rs, src/verify.rs
Also fixes some clippy errors.
=> make verify_one public

src/bit_set.rs, src/comment_parser.rs, src/database.rs, src/diag.rs, src/export.rs, src/formula.rs, src/grammar.rs, src/line_cache.rs, src/main.rs, src/nameck.rs, src/parser.rs, src/parser_tests.rs, src/scopeck.rs, src/segment.rs, src/segment_set.rs, src/statement.rs, src/verify.rs
One lint had to be silenced because of rust-lang/rust-clippy#10296.
=> clippy fixes

Cargo.lock
Trivial PR: This is just the output of running cargo update.
=> Updating the dependencies

src/diag.rs
=> Fix 'missing contributor' error message

src/comment_parser.rs, src/comment_parser_tests.rs
For consistency with metamath-exe.
=> trim spaces before/after math mode and labels

src/parser.rs, src/statement.rs
=> make HeadingComment public

src/grammar.rs, src/grammar_tests.rs
These are the changes required to make the minimal database from #137 pass.
Details below.
=> Fix for #135

metamath-rs/src/comment_parser.rs, metamath-rs/src/comment_parser_tests.rs
=> parse `\r\n` in discouragements

metamath-rs/src/comment_parser.rs, metamath-rs/src/verify_markup.rs
Fixed clippy warnings after rustup to 1.84.0.
=> Clippy 1.84.0

metamath-rs/src/database.rs
=> The database needs to be parsed with incremental mode for grammar
