metamath/metamath-knife

src/segment_set.rs, src/util.rs, src/verify.rs
Remove unnecessary clone() calls; they take more time & removing them
makes the code simpler.
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>
=> Remove unnecessary clone() calls

.github/workflows/verify.yml
Ubuntu 16 isn't working properly on GitHub, and its support
will be removed soon (2021-09-20), so let's remove it from
the test matrix.
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>
=> Remove Ubuntu 16 from GitHub Actions test matrix

Cargo.lock, Cargo.toml, src/database.rs, src/diag.rs, src/grammar.rs, src/grammar_tests.rs, src/main.rs
This adds several new grammar tests:
- a new "Verify Parse Statements" command line, which "flattens" the formula trees and verifies that each formula matches the original.
- cargo tests for a minimal database with "garden paths",
- cargo tests for some grammar errors,
Also, the `parse_formula` function was recursive, which required many function arguments. This function is now iterative, and much fewer arguments are required.
=> Additional grammar tests, iterative parsing

src/grammar.rs, src/grammar_tests.rs
This makes the `grammar` module's `parse_formula` function public, by:
- using an iterator over symbols, rather than a reference to a database statement,
- removing the private `formula_builder` from its parameters.
This change allows a user of the library to parse not just existing database statements, but also new statements, without the need to add them to the database.
=> Extracted a `parse_formula` library API to parse a single formula

src/formula.rs, src/tree.rs
This (shall) make copying and extracting sub-formulas cheaper.
=> `Formula` is now using `Arc`

src/grammar.rs, src/grammar_tests.rs, src/lib.rs
This is the case where one of the type codes expected appears as a substring of the expression to be parsed.
Also added handling a "FloatNotVariable" error case.
=> Handling a special case

src/diag.rs
=> Fix for diagnostic span at the start of a line

src/formula.rs, src/grammar.rs, src/grammar_tests.rs
* Adds an API to iterate through a list of substitutions,
* This also fixes grammatical parsing for a special case (`class x`, which was not recognized as a simple [cv, vx]).
=> Substitution API, Grammar fix

src/database.rs, src/outline.rs, src/tree.rs
* `Outline` no longer implements `Default`. (The default value was not a valid outline, because the `root` index was out of bounds of the tree.)
* `build_outline()` now returns the `Outline` instead of modifying the default value.
* The implementation of `build_outline` has been refactored:
* less `unwrap`s needed
* Use a single `sibling_stack` instead of a vector-of-vectors for fewer allocations
=> refactor outline construction

src/database.rs, src/diag.rs, src/grammar.rs, src/lib.rs, src/main.rs, src/outline.rs, src/parser.rs, src/parser_tests.rs, src/segment_set.rs, src/typesetting.rs
This extends the `$j` command parser a bit to handle the contents of the `$t` comment, and adds a complete parser for `$t` commands. I'm thinking about writing a web site generator, but I'm not sure whether all the metamath hacks belong in this repo, so maybe it should just be a separate crate (and/or repo) which uses this library for parsing.
=> add $t comment parser

src/comment_parser.rs, src/comment_parser_tests.rs, src/lib.rs, src/parser.rs
This lets us parse metamath's pseudo-markdown syntax in comments:
```
$( You can do _italics_, sub_scripts, <HTML>(basically <B>verbatim</b>)</HTML> blocks,
~ label references and ~ http://web-site.com references, and ` ( math + strings ) ` .
Also paragraph breaks and [Biblio] references.
This last bit is not parsed, these markers are handled separately from markup parsing:
(Contributed by Mario Carneiro, 28-Jan-2022.) $)
foo $a |- ( ph -> ph ) $.
```
=> add comment markup parser

Cargo.lock, Cargo.toml, src/comment_parser.rs, src/comment_parser_tests.rs, src/database.rs, src/diag.rs, src/export.rs, src/lib.rs, src/main.rs, src/outline.rs, src/parser.rs, src/scopeck.rs, src/segment.rs, src/segment_set.rs, src/statement.rs, src/typesetting.rs, src/verify.rs, src/verify_markup.rs
This replicates the functionality of metamath.exe's `VERIFY MARKUP` command. New checks:
1. Labels should not contain `_`
2. Labels should not start with `mm`
3. Labels should not match reserved windows filenames `CON, PRN, AUX` etc
4. If there is an axiom `ax-foo` with a corresponding `axfoo` axiom/theorem then they should match
5. Axioms that prove `|- ...` should have a name `ax-*` or `df-*`
6. Tokens should not use the `@` and `?` characters
7. Every token should have a `htmldef` command
8. Use of the author `?who?` is forbidden
9. Dates should parse
10. Parentheticals should come in chronological order
11. Axioms and theorems (except for syntax axioms) should have a `Contributed by` comment
12. There should not be two `Contributed by` comments
13. The `Contributed by` comment should …
=> add verify markup pass

src/diag.rs, src/grammar.rs, src/grammar_tests.rs
This is a follow-up to my previous changes regarding parsing Metamath statements from a string.
The `StmtParseError` generated in that case now refer to spans in that string, rather than an index in the math tokens.
This makes error handling easier.
=> Statement parse errors now refer to spans

src/lib.rs, src/outline.rs, src/segment.rs, src/statement.rs
The `SegmentOrder` which allows to compare statement addresses and token addresses is private.
This implements the `Comparer` trait for the `Database`, so that comparing statement addresses is possible on the API.
=> Implement `Comparer` trait for the Database

src/grammar.rs, src/grammar_tests.rs
Edit this fixes the case when tokens in a math string are not separated by single, but multiple whitespaces.
With these changes, `metamath-knife` does not attempt to resolve the "empty" tokens in between.
=> String parsing : fix issue with multiple whitespaces in a row

src/formula.rs, src/formula_tests.rs
I recently dug up my [rumm](https://github.com/tirix/rumm) proof of concept and found out in some cases I need not just substitution of variables, but also substitution of whole sub-formulas. 
This adds this functionality, together with the relevant test.
=> Substitute sub-formulas

src/database.rs, src/export.rs, src/proof.rs
This makes it possible to disable expr collection inside `ProofTreeArray`, which is not required when the goal is to build a compressed proof. It also exposes `ProofTreePrinter` (although possibly the API could use some work) so that it is possible to generate compressed proofs without going through MMP. Eventually it would be nice to have a proof editing interface like metamath.exe's `save proof`; I already have some use cases for that but probably won't be able to get to it soon.
=> expose ProofTreePrinter, make enable_exprs optional

src/database.rs, src/discouraged.rs, src/lib.rs, src/main.rs
This adds a `-D` or `--discouraged` flag to the command line version of the tool to generate the `discouraged` file, in the same format as metamath.exe.
=> Generate `discouraged` file

src/main.rs
I prefer this control flow for `discouraged` in main.rs, I think it's clearer than the dummy closure.
I wanted to push this on the previous pull request but I was just one minute too slow!
=> Discouraged control flow

README.md, src/database.rs, src/main.rs
@benjub [mentioned](https://github.com/david-a-wheeler/metamath-knife/pull/96#issuecomment-1436529780) that some verbs in the command line help are "Prints" instead of "Print". Actually those two exceptions are for help and version, which are automatically generated by the `clap` crate. So I instead changed all our option descriptions so that they are verbs at the 3rd person.
Also, fixes #101 by running a grammar pass before printing the grammar.
=> Verbs for command line help, README, and Misc.

src/formula.rs, src/grammar.rs, src/main.rs
Adds a new public API `convert_typecode` to convert a formula to a given typecode.
This is typically used to convert a formula with typecode `set` to `class`.
=> Formula typecode converter

src/database.rs, src/diag.rs, src/main.rs
As pointed out in https://github.com/david-a-wheeler/metamath-knife/pull/107#discussion_r1181545930, if you use the command line options to e.g. enable the verify pass but not the scope pass, the errors from the scope pass will not be reported (and this could potentially make the program report no errors and give an OK error code even though there were errors).
In this PR we simplify the interface to eliminate the `DiagnosticClass` enum to filter error results and always report errors from all passes that have been run (and by selecting different options you change which passes run).
=> always report all errors

src/main.rs
When I was trying to run an export statement, I was getting:
```
0 diagnostics issued.
thread 'main' panicked at 'The database has not run `name_pass()`. Please ensure it is run before calling depending methods.', src/database.rs:530:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This PR fixes it. 
Discussion:
If you want to make a helper function that calls name_pass and scope_pass, I am happy to provide it. 
Testplan:
run an export command like:
```
cargo run ~/Downloads/metamath/set.mm --export fzval
```
and see that it runs through.
=> Fixing the running of export statements

Cargo.lock, Cargo.toml, src/export_deps.rs, src/lib.rs, src/main.rs, src/util_tests.rs
As per discussion on the google groups:
This adds a new option `--export-graphml-deps [FILE]` (no shortcut), which allows to export the theorem dependencies in [GraphML](http://graphml.graphdrawing.org/) format.
Requires to be compiled with the `xml` feature.
=> Add function to export theorem dependencies in GraphML format

Cargo.lock, Cargo.toml, src/axiom_use.rs, src/database.rs, src/diag.rs, src/lib.rs, src/main.rs, src/parser.rs, src/usage_tests.rs
Naive but functional axiom usage check.
Introduces a `-u` option which checks that `$j usage 'xxx' avoids 'yyy'` commands are respected.
This only checks axioms dependencies, not all statements.
Currently issues an "Unknown label" diagnostic if the axiom declared as avoided actually only declared further down in the database. This is the simpler implementation, but this generates many warnings with the current `set.mm`.
=> Axiom usage verification

src/comment_parser.rs, src/grammar.rs, src/parser.rs, src/statement.rs
This adds support for strings like `"ab""c"` in $t and $j comments which encode the string `ab"c`. 
Some additional care is required in user code, since now the body of a string is no longer the actual contents of the string but rather doubled characters have to be unescaped. We return a `Cow` now and check for the very common case of no escapes to avoid the copy most of the time. But if working directly with string spans, `CommandToken::unescape_string` should be used to get the value now.
=> add double-quote escape in $t/$j comments

src/axiom_use.rs, src/lib.rs, src/main.rs, src/parser.rs
As suggested by @GinoGiotto in [a comment in #3399](https://github.com/metamath/set.mm/pull/3399#issuecomment-1685310104), this adds an option to get direct of indirect usage of theorems, given by the list of their labels.
=> Add a "statement use" option

src/comment_parser.rs, src/comment_parser_tests.rs
This is to align with change done in metamath/metamath-exe#160, to handle cases discovered in metamath/set.mm#3389.
Before these changes, double underscores were treated as subscript. They are now correctly ignored and returned as a single span.
~~To be complete, in addition to these changes, the `unescape_text` function in `CommentItem` should also transform double underscores into single underscores. @digama0, what's your proposal for those?~~
=> Add handling for double underscores

src/database.rs
needed by mm-web-rs, and easy enough to expose.
=> add comparison by label/atom/address

src/diag.rs
As seen in https://github.com/metamath/set.mm/actions/runs/6345667560/job/17238038357?pr=3522 the "__" is interpreted as the markdown bold syntax, so this should be escaped
EDIT: This is kinda weird since there are no underscores at the end of the message...
=> fix error formatting bug

src/main.rs
=> call grammar_pass before export_grammar_dot

src/scopeck.rs
Used by mm-web-rs, a convenience method for getting the constants in an expression, including the `rump` at the end.
=> add const_ranges iterator

src/grammar.rs, src/grammar_tests.rs
This makes the errors occur at the first point where the string fails to parse, even if there are missing tokens toward the end. Also it avoids some allocations for the string in the middle.
=> lazy fail on parse errors

.github/workflows/verify.yml, src/comment_parser.rs, src/parser.rs, src/verify_markup.rs
First of all, use the develop branch rather than the master branch because the latter is rather old and we haven't been using it.
Second of all, add --verify-markup and --parse-typesetting so that we run more of the checks (including most notably the ones which the set.mm automated checks enable).
This pull request replaces #135 which was the first attempt at this.
=> Fix set.mm check

src/grammar.rs
These are the code cleanup changes from #137. The only actual functionality change here is that `syntax 'A' 'B';` parses as intended. The rest is just using `let else` more and some typos in panic messages.
=> support `syntax 'A' 'B' 'C';` command, style

src/nameck.rs, src/verify.rs
This fixes the issue in CI found after #144 was merged, because of the new clippy version 1.73.0.
=> Clippy update

Cargo.lock, metamath-rs/Cargo.toml, metamath-rs/src/bit_set.rs, metamath-rs/src/comment_parser.rs, metamath-rs/src/export.rs, metamath-rs/src/parser.rs, metamath-rs/src/verify_markup.rs
[`once_cell`](https://docs.rs/once_cell/latest/once_cell/) is preferred over `lazy_static`, and it was recently standardized as `std::sync::OnceLock` in rustc 1.70.
=> switch from lazy_static to std::sync::OnceLock

metamath-rs/src/util.rs
This is a workaround for the new Rust 1.78 precondition checks which made CI for #158 fail.
=> Fix UB from precondition violations caught in rust 1.78

Cargo.lock, metamath-knife/Cargo.toml, metamath-knife/src/main.rs, metamath-rs/Cargo.toml, metamath-rs/src/diag.rs, metamath-rs/src/lib.rs, metamath-rs/src/verify_markup.rs
This uses the `html5ever` crate to parse HTML in `<HTML>` blocks and report any errors. Unfortunately, the error messages are kind of garbage (no positional information), so the best we can do is point at the containing block. To make the results more actionable, I manually copied the text from offending theorems to the [validator](https://validator.w3.org/nu/), which has better error messages.
Since it's a bit of a chunky dependency, it has been added as an optional dependency (it's possible to compile without it in which case you don't get the `verify_markup` function).
=> HTML validation in verify markup

metamath-rs/src/grammar.rs
Currently, `--dump-formula` dumps formulas pretty-printed to token sequences, which defeats the purpose of parsing them in the first place. This makes the command more useful by printing the output as a sexpr instead, so it is easier to see the actual parse tree that resulted.
=> dump formulas as s-exprs

metamath-knife/src/main.rs, metamath-rs/src/database.rs, metamath-rs/src/grammar.rs
Make it return a list of errors and print them, instead of just dropping the result and always reporting no errors.
=> --verify-parse-stmt does nothing

metamath-rs/src/bit_set.rs, metamath-rs/src/comment_parser.rs, metamath-rs/src/database.rs, metamath-rs/src/formula.rs, metamath-rs/src/parser.rs, metamath-rs/src/proof.rs, metamath-rs/src/segment.rs, metamath-rs/src/statement.rs, metamath-rs/src/tree.rs, metamath-rs/src/util.rs
Fixed clippy warnings after rustup to rustc 1.83.0.
=> Clippy fixes

metamath-rs/src/diag.rs, metamath-rs/src/parser.rs, metamath-rs/src/parser_tests.rs, metamath-rs/src/statement.rs
Fixes #174 
Adds two more error checks when parsing `$t` and `$j` commands:
- checks that a command is properly closed with a semicolon,
- checks that a space or a semicolon must always follow a quoted command token (`String`).
Adds the corresponding tests, and more.
=> Fix for #174, more parser checks and more parser tests

metamath-rs/src/axiom_use.rs, metamath-rs/src/usage_tests.rs
Because the `usage` command was checking the database in a single pass, it did not know about axioms after the current cursor, and was assuming that these axioms existed and were not used.
However, this has the side effect of not being able to report unknown labels in usage commands.
This PR fixes this, and reports unknown labels in usage commands.
One test added.
This is a follow-up of #175: Following that PR, a missing space between two `usage` labels like in `$j 'exel' avoids 'ax-10''ax-13';` will now be parsed as refering to `ax-10'ax-13` (doubled quote as escape). To be complete, the tool now needs to report this unknown label.
=> Check for unknown labels in usage commands

metamath-rs/src/grammar.rs
Printing in hashmap order is bad because it is both visibly random and also nondeterministic.
=> dump formulas in source order

metamath-rs/src/database.rs
This fixes using the library in WebAssembly, which panics when `Instant::now()` is called.
https://github.com/rust-lang/rust/blob/1d55f7270dc6fda5c19da3f563e91165d07463c4/library/std/src/sys/pal/wasm/mod.rs#L36-L37
https://github.com/rust-lang/rust/blob/1d55f7270dc6fda5c19da3f563e91165d07463c4/library/std/src/sys/pal/unsupported/time.rs#L11-L14
=> Avoid calling `Instant::now()` when timing disabled

README.md
technically there's no difference since david-a-wheeler points to metamath but updating it is more sane so users don't have to check
=> correct download link
